# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 10
  start_block: 0
  contracts:
  - name: OptimismGovernorV6
    address:
    - 0x0c01693a1A4C46cf9A5F56c99304EBB35C4E817a
    - 0xcDF27F107725988f2261Ce2256bDfCdE8B382B10
    handler: src/EventHandlers.ts
    events:
    - event: Initialized(uint8 version)
    - event: ProposalCanceled(uint256 proposalId)
    - event: ProposalCreated(uint256 indexed proposalId, address indexed proposer, address[] targets, uint256[] values, string[] signatures, bytes[] calldatas, uint256 startBlock, uint256 endBlock, string description, uint8 proposalType)
    - event: ProposalDeadlineUpdated(uint256 proposalId, uint64 deadline)
    - event: ProposalExecuted(uint256 proposalId)
    - event: ProposalThresholdSet(uint256 oldProposalThreshold, uint256 newProposalThreshold)
    - event: ProposalTypeUpdated(uint256 indexed proposalId, uint8 proposalType)
    - event: QuorumNumeratorUpdated(uint256 oldQuorumNumerator, uint256 newQuorumNumerator)
    - event: VoteCast(address indexed voter, uint256 proposalId, uint8 support, uint256 weight, string reason)
    - event: VoteCastWithParams(address indexed voter, uint256 proposalId, uint8 support, uint256 weight, string reason, bytes params)
    - event: VotingDelaySet(uint256 oldVotingDelay, uint256 newVotingDelay)
    - event: VotingPeriodSet(uint256 oldVotingPeriod, uint256 newVotingPeriod)
rollback_on_reorg: false
